#!/usr/bin/python3
# vim:et:sta:sts=4:sw=4:ts=8:tw=79:

'''
    wm-logout - present a dialog to perform power management actions or
    logout from a window manager
    
    it requires: elogind
'''

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import os
import sys


# Internationalization
import locale
import gettext
locale.setlocale(locale.LC_ALL, '')
locale.bindtextdomain("wm-logout", "/usr/share/locale")
gettext.bindtextdomain("wm-logout", "/usr/share/locale")
gettext.textdomain("wm-logout")
_ = gettext.gettext
	
class WMLogout(Gtk.Window):

    def __init__(self):

        # Set up GTK window
        Gtk.Window.__init__(self, title=(_("Exit")))
        
        icon_size = Gtk.IconSize.BUTTON
        btn_border_size = 6
        self.set_deletable(False)
        self.set_resizable(False)
        self.set_position(1)
        self.connect("delete_event", self.cancel)
        self.set_border_width(int(1.5*btn_border_size))
        self.connect("destroy", Gtk.main_quit)
    
        # Create a box to pack other widgets into
        self.box_vert = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=2)
        self.add(self.box_vert)

        # Create label
        self.lbl_message = Gtk.Label(_("Please select an action:"))
        self.box_vert.pack_start(self.lbl_message, True, True, 0)
        self.lbl_message.show()

        # Create a box for the top row of buttons
        self.box_top = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
        self.box_vert.pack_start(self.box_top, True, True, 0)

        # Create a box for the middle row of buttons
        self.box_middle = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
        self.box_vert.pack_start(self.box_middle, True, True, 0)
        
        # Create a box for the bottom row of buttons
        self.box_bottom = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
        self.box_vert.pack_start(self.box_bottom, True, True, 0)
        
        # Create shutdown button
        self.btn_shutdown = Gtk.Button(_("_Shutdown"), None, True)         # Instantiate button
        self.btn_shutdown.set_border_width(btn_border_size)             # Set border width to sane amount        
        self.image = Gtk.Image();
        self.image.set_from_icon_name("gnome-shutdown", icon_size)
        self.btn_shutdown.set_property('image', self.image)
        self.btn_shutdown.connect("clicked", self.shutdown)             # Connect event handler
        self.box_top.pack_start(self.btn_shutdown, True, True, 0)       # Insert into the correct layout box
        self.btn_shutdown.show()                                        # Show button
        
        
        # Now repeat for remaining buttons
        
        # Create logout button
        self.btn_logout = Gtk.Button(_("_Log out"), None, True)
        self.btn_logout.set_border_width(btn_border_size)        
        self.image = Gtk.Image()
        self.image.set_from_icon_name("gnome-logout", icon_size)
        self.btn_logout.set_property('image', self.image)
        self.btn_logout.connect("clicked", self.logout)
        self.box_middle.pack_start(self.btn_logout, True, True, 0)
        self.btn_logout.show()
        
        # Create reboot button
        self.btn_reboot = Gtk.Button(_("_Reboot"), None, True)
        self.btn_reboot.set_border_width(btn_border_size)
        self.image = Gtk.Image()
        self.image.set_from_icon_name("reload", icon_size)
        self.btn_reboot.set_property('image', self.image)
        self.btn_reboot.connect("clicked", self.reboot)
        self.box_middle.pack_start(self.btn_reboot, True, True, 0)
        self.btn_reboot.show()

        # Create suspend button
        self.btn_suspend = Gtk.Button(_("_Suspend"), None, True)
        self.btn_suspend.set_border_width(btn_border_size)
        self.image = Gtk.Image()
        self.image.set_from_icon_name("gnome-session-suspend", icon_size)
        self.btn_suspend.set_property('image', self.image)
        self.btn_suspend.connect("clicked", self.suspend)
        self.box_middle.pack_start(self.btn_suspend, True, True, 0)
        self.btn_suspend.show()

        # Create hibernate button
        self.btn_hibernate = Gtk.Button(_("_Hibernate"), None, True)
        self.btn_hibernate.set_border_width(btn_border_size)
        self.image = Gtk.Image()
        self.image.set_from_icon_name("gnome-session-hibernate", icon_size)
        self.btn_hibernate.set_property('image', self.image)
        self.btn_hibernate.connect("clicked", self.hibernate)
        self.box_middle.pack_start(self.btn_hibernate, True, True, 0)
        self.btn_hibernate.show()

        # Create cancel button
        self.btn_cancel = Gtk.Button(_("_Cancel"), None, True)
        self.btn_cancel.set_border_width(btn_border_size)
        self.image = Gtk.Image()
        self.image.set_from_icon_name("gtk-cancel",icon_size)
        self.btn_cancel.set_property('image', self.image)
        self.btn_cancel.connect("clicked", self.cancel, 'Cancelled')
        self.box_vert.pack_start(self.btn_cancel, True, True, 0)
        self.btn_cancel.show()

        self.box_top.show()
        self.box_middle.show()
        self.box_bottom.show()
        self.box_vert.show()
        self.set_focus(self.btn_logout)
        
    # Cancel/exit
    def cancel(self, widget=None, event=None, data=None):
        Gtk.main_quit()
        return False

    # Logout
    def logout(self, widget=None):
        os.system('openbox --exit')
        #os.system('xlogout')
        
    # Reboot
    def reboot(self, widget=None):
        os.system('loginctl reboot')

    # Shutdown
    def shutdown(self, widget=None):
        os.system('loginctl poweroff')

    # Suspend
    def suspend(self, widget=None):
        os.system('loginctl suspend')

    # Hibernate
    def hibernate(self, widget=None):
        os.system('loginctl hibernate')
        
if __name__ == "__main__":
    app = WMLogout()
    app.show_all()
    Gtk.main()
